### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by saroele**
* many new zone models
* graphical improvements
* example of two-zone models (work in progress)
* stochastic zones (having a stochastic capacitor), developed for moving horizon state estimation (contributed by @matsvandecavey)

### CODE REVIEW

**Comment by rubenbaetens** [comment]
@saroele i only did graphical changes, so it's up to you which graphics you prefer ;) i actually just made the symbols of R's, C's and Windows etc. consistent with ```IDEAS``` and used the green the distinct 'idealized' models compared to ```IDEAS```.

**Comment by saroele** [comment]
This will be for the weekend.  Ik zal zien of ik uw symbolen makkelijk kan mergen bovenop de pull request.

**Comment by saroele** [comment]
@rubenbaetens 
I was not convinced by the changed window and zone.  But I love the new simFasBui and HVAC.  So it has become a 50/50 split.  Please have a look at the current look and let me know what you'd like to change.  Thanks for the contribution.

**Comment by rubenbaetens** [comment]
@saroele is it OK to update FastBuildings to MSL 3.2.1 ?

**Comment by saroele** [comment]
dunno, but i think so. that could even be the solution to all the warnings
i get from the SI subpackage...

**Pull request merged**
